image: node:current-alpine

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - mv public public-vue
    - mv dist public

  artifacts:
    expire_in: 1 day
    paths:
      - public

  only:
    - master
